package modelo.entidad;
// Generated 23-oct-2020 16:53:23 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Alquiler generated by hbm2java
 */
public class Alquiler  implements java.io.Serializable {


     private Integer idalquiler;
     private Bicicleta bicicleta;
     private Cliente cliente;
     private TipoPago tipoPago;
     private Usuario usuario;
     private Date fechaPrestamo;
     private Date fechaEntrega;
     private Integer horas;
     private Double totalPagar;
     private Date fechaCreacion;

    public Alquiler() {
    }

    public Alquiler(Bicicleta bicicleta, Cliente cliente, TipoPago tipoPago, Usuario usuario, Date fechaPrestamo, Date fechaEntrega, Integer horas, Double totalPagar, Date fechaCreacion) {
       this.bicicleta = bicicleta;
       this.cliente = cliente;
       this.tipoPago = tipoPago;
       this.usuario = usuario;
       this.fechaPrestamo = fechaPrestamo;
       this.fechaEntrega = fechaEntrega;
       this.horas = horas;
       this.totalPagar = totalPagar;
       this.fechaCreacion = fechaCreacion;
    }
   
    public Integer getIdalquiler() {
        return this.idalquiler;
    }
    
    public void setIdalquiler(Integer idalquiler) {
        this.idalquiler = idalquiler;
    }
    public Bicicleta getBicicleta() {
        return this.bicicleta;
    }
    
    public void setBicicleta(Bicicleta bicicleta) {
        this.bicicleta = bicicleta;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public TipoPago getTipoPago() {
        return this.tipoPago;
    }
    
    public void setTipoPago(TipoPago tipoPago) {
        this.tipoPago = tipoPago;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaPrestamo() {
        return this.fechaPrestamo;
    }
    
    public void setFechaPrestamo(Date fechaPrestamo) {
        this.fechaPrestamo = fechaPrestamo;
    }
    public Date getFechaEntrega() {
        return this.fechaEntrega;
    }
    
    public void setFechaEntrega(Date fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }
    public Integer getHoras() {
        return this.horas;
    }
    
    public void setHoras(Integer horas) {
        this.horas = horas;
    }
    public Double getTotalPagar() {
        return this.totalPagar;
    }
    
    public void setTotalPagar(Double totalPagar) {
        this.totalPagar = totalPagar;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }




}


