package modelo.entidad;
// Generated 23-oct-2020 16:53:23 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bicicleta generated by hbm2java
 */
public class Bicicleta  implements java.io.Serializable {


     private Integer idbicicleta;
     private Color color;
     private Estado estado;
     private Marca marca;
     private Proveedor proveedor;
     private Sucursal sucursal;
     private Tipo tipo;
     private String descripcion;
     private Date fechaCreacion;
     private Set<Alquiler> alquilers = new HashSet<Alquiler>(0);

    public Bicicleta() {
    }

    public Bicicleta(Color color, Estado estado, Marca marca, Proveedor proveedor, Sucursal sucursal, Tipo tipo, String descripcion, Date fechaCreacion, Set<Alquiler> alquilers) {
       this.color = color;
       this.estado = estado;
       this.marca = marca;
       this.proveedor = proveedor;
       this.sucursal = sucursal;
       this.tipo = tipo;
       this.descripcion = descripcion;
       this.fechaCreacion = fechaCreacion;
       this.alquilers = alquilers;
    }
   
    public Integer getIdbicicleta() {
        return this.idbicicleta;
    }
    
    public void setIdbicicleta(Integer idbicicleta) {
        this.idbicicleta = idbicicleta;
    }
    public Color getColor() {
        return this.color;
    }
    
    public void setColor(Color color) {
        this.color = color;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Set<Alquiler> getAlquilers() {
        return this.alquilers;
    }
    
    public void setAlquilers(Set<Alquiler> alquilers) {
        this.alquilers = alquilers;
    }




}


