package modelo.entidad;
// Generated 23-oct-2020 16:53:23 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idcliente;
     private Usuario usuario;
     private String NDocumento;
     private String nombre;
     private String apellido;
     private String telefono;
     private String direccion;
     private Date fechaCreacion;
     private Set<Alquiler> alquilers = new HashSet<Alquiler>(0);

    public Cliente() {
    }

    public Cliente(Usuario usuario, String NDocumento, String nombre, String apellido, String telefono, String direccion, Date fechaCreacion, Set<Alquiler> alquilers) {
       this.usuario = usuario;
       this.NDocumento = NDocumento;
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefono = telefono;
       this.direccion = direccion;
       this.fechaCreacion = fechaCreacion;
       this.alquilers = alquilers;
    }
   
    public Integer getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(Integer idcliente) {
        this.idcliente = idcliente;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNDocumento() {
        return this.NDocumento;
    }
    
    public void setNDocumento(String NDocumento) {
        this.NDocumento = NDocumento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Set<Alquiler> getAlquilers() {
        return this.alquilers;
    }
    
    public void setAlquilers(Set<Alquiler> alquilers) {
        this.alquilers = alquilers;
    }




}


