package modelo.entidad;
// Generated 23-oct-2020 16:53:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Marca generated by hbm2java
 */
public class Marca  implements java.io.Serializable {


     private Integer idmarca;
     private String nombre;
     private Set<Bicicleta> bicicletas = new HashSet<Bicicleta>(0);

    public Marca() {
    }

    public Marca(String nombre, Set<Bicicleta> bicicletas) {
       this.nombre = nombre;
       this.bicicletas = bicicletas;
    }
   
    public Integer getIdmarca() {
        return this.idmarca;
    }
    
    public void setIdmarca(Integer idmarca) {
        this.idmarca = idmarca;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Bicicleta> getBicicletas() {
        return this.bicicletas;
    }
    
    public void setBicicletas(Set<Bicicleta> bicicletas) {
        this.bicicletas = bicicletas;
    }




}


