package modelo.entidad;
// Generated 23-oct-2020 16:53:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private Integer idproveedor;
     private String nombre;
     private Set<Bicicleta> bicicletas = new HashSet<Bicicleta>(0);

    public Proveedor() {
    }

    public Proveedor(String nombre, Set<Bicicleta> bicicletas) {
       this.nombre = nombre;
       this.bicicletas = bicicletas;
    }
   
    public Integer getIdproveedor() {
        return this.idproveedor;
    }
    
    public void setIdproveedor(Integer idproveedor) {
        this.idproveedor = idproveedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Bicicleta> getBicicletas() {
        return this.bicicletas;
    }
    
    public void setBicicletas(Set<Bicicleta> bicicletas) {
        this.bicicletas = bicicletas;
    }




}


