package modelo.entidad;
// Generated 23-oct-2020 16:53:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sucursal generated by hbm2java
 */
public class Sucursal  implements java.io.Serializable {


     private Integer idsucursal;
     private String nombre;
     private Set<Bicicleta> bicicletas = new HashSet<Bicicleta>(0);
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Sucursal() {
    }

    public Sucursal(String nombre, Set<Bicicleta> bicicletas, Set<Usuario> usuarios) {
       this.nombre = nombre;
       this.bicicletas = bicicletas;
       this.usuarios = usuarios;
    }
   
    public Integer getIdsucursal() {
        return this.idsucursal;
    }
    
    public void setIdsucursal(Integer idsucursal) {
        this.idsucursal = idsucursal;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Bicicleta> getBicicletas() {
        return this.bicicletas;
    }
    
    public void setBicicletas(Set<Bicicleta> bicicletas) {
        this.bicicletas = bicicletas;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


