package modelo.entidad;
// Generated 23-oct-2020 16:53:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipo generated by hbm2java
 */
public class Tipo  implements java.io.Serializable {


     private Integer idtipo;
     private String nombre;
     private Integer tamano;
     private Set<Bicicleta> bicicletas = new HashSet<Bicicleta>(0);

    public Tipo() {
    }

    public Tipo(String nombre, Integer tamano, Set<Bicicleta> bicicletas) {
       this.nombre = nombre;
       this.tamano = tamano;
       this.bicicletas = bicicletas;
    }
   
    public Integer getIdtipo() {
        return this.idtipo;
    }
    
    public void setIdtipo(Integer idtipo) {
        this.idtipo = idtipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getTamano() {
        return this.tamano;
    }
    
    public void setTamano(Integer tamano) {
        this.tamano = tamano;
    }
    public Set<Bicicleta> getBicicletas() {
        return this.bicicletas;
    }
    
    public void setBicicletas(Set<Bicicleta> bicicletas) {
        this.bicicletas = bicicletas;
    }




}


